### ISSUE TITLE
Deadline exceeded when drivers cannot be allocated (even if the client provides context.Background())

### ISSUE THREAD

**Issue by smola** [bblfsh/bblfshd#229] opened 2018-12-13 11:44 UTC
Possibly duped or related to #227 #209 

Using `bblfshd:2.11.0-drivers` image.

bblfshd logs:
```
time="2018-12-13T11:42:21Z" level=warning msg="unable to allocate a driver instance: context deadline exceeded" language=go
time="2018-12-13T11:42:21Z" level=error msg="request processed content 6534844 bytes error: context deadline exceeded" elapsed=6.198363245s language=go
```

client logs:
```
rpc error: code = Unknown desc = context deadline exceeded
```

Code to reproduce:
```go
package main

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"
	"runtime"
	"sync"
	"sync/atomic"

	bblfsh "gopkg.in/bblfsh/client-go.v3"
)

func main() {

	url := `https://raw.githubusercontent.com/src-d/enry/master/data/frequencies.go`
	resp, err := http.DefaultClient.Get(url)
	if err != nil {
		panic(err)
	}

	bs, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		panic(err)
	}

	code := string(bs)

	client, err := bblfsh.NewClient("0.0.0.0:9432")
	if err != nil {
		panic(err)
	}

	wg := sync.WaitGroup{}
	var count int32
	for i := 0; i < runtime.NumCPU()*2; i++ {
		wg.Add(1)
		go func() {
			for {
				_, _, err = client.
					NewParseRequest().
					Context(context.Background()).
					Language("go").
					Content(code).
					UAST()
				if err != nil {
					fmt.Println(err)
				}

				newCount := atomic.AddInt32(&count, 1)
				if newCount%100 == 0 {
					fmt.Printf("Requests: %d\n", newCount)
				}
			}
			wg.Done()
		}()
	}
	wg.Wait()
}
```

**Comment by smacker** [comment] 2019-01-25 16:34
I'm having the same issue with csharp driver. Most probably it takes more than 5 seconds to start it on my system and:
```
[2019-01-23T16:37:35Z]  INFO driver csharp installed "bblfsh/csharp-driver:latest"
[2019-01-23T16:39:06Z]  INFO csharp-driver version: v0.2.0 (build: 2019-01-22T15:05:36Z) id=01d1xs8h4919r040kregr8qr3p language=csharp
[2019-01-23T16:39:06Z]  INFO server listening in /tmp/rpc.sock (unix) id=01d1xs8h4919r040kregr8qr3p language=csharp
[2019-01-23T16:39:49Z]  WARN unable to allocate a driver instance: context deadline exceeded language=csharp
[2019-01-23T16:39:49Z] ERROR request processed content 343 bytes error: context deadline exceeded elapsed=5.0019308s filename=hello.java language=csharp
```

Looks like timeout is triggered by this value: https://github.com/bblfsh/bblfshd/blob/master/daemon/pool.go#L24
I tried to change timeout in context of the client but no luck.

**Comment by dennwc** [comment] 2019-01-25 16:48
I'm working right now to fix some timeout issues, and I think the general consensus is to remove default timeout from `bblfshd` and let the client decide. I will fix it shortly.

**Comment by dennwc** [comment] 2019-01-31 17:43
Probably broken by https://github.com/bblfsh/bblfshd/commit/e5ca340b55a841234e7a66089ca8ffcc3ec33e66

**Comment by smacker** [comment] 2019-02-06 12:30
Looks like the issue is solved: https://github.com/bblfsh/csharp-driver/issues/25

**Comment by dennwc** [comment] 2019-02-06 12:55
@smacker Is it? What is different now?

**Comment by smacker** [comment] 2019-02-06 13:25
There is no `context deadline exceeded` error anymore, request runs forever with `context.Background()`.

**Comment by dennwc** [comment] 2019-02-06 13:49
Awesome! It means you are using the v2 API under the hood. I'll close this one then. Thanks for checking it!

**Closed by dennwc** 2019-02-06 13:49 UTC
Labels: bug
