### ISSUE TITLE
bblfshctl driver install fails for installed drivers

### ISSUE THREAD

**Issue by carlosms** [bblfsh/bblfshd#195] opened 2018-10-01 10:27 UTC
With v2.8.0, a `driver install` for an already installed driver exits with 1, which is a breaking change that breaks CI for gitbase-web.
The output also seems to be off (contains `%s`, and prints the usage help):

```
$ docker exec -it bblfshd bblfshctl driver install go docker://bblfsh/go-driver:latest
Installing go language driver from "docker://bblfsh/go-driver:latest"... Error
Error, driver already installed: go (image reference: docker://bblfsh/go-driver:latest): %s
[driver already installed: go (image reference: docker://bblfsh/go-driver:latest): %s]

Usage:
  bblfshctl [OPTIONS] driver install [install-OPTIONS] [language] [image]

Installs a new driver for a given language

Using `--all` all the official bblfsh driver are install in the
daemon. Using `--recommended` will only install the recommended,
more developed. Using `language` and `image` positional arguments
one single driver can be installed or updated.

Image reference format should be `[transport]name[:tag]`.
Defaults are 'docker://' for transport and 'latest' for tag.

Help Options:
  -h, --help              Show this help message

[install command options]
          --update        replace the current image for the language if any
          --all           installs all the official drivers
          --recommended   install the recommended official drivers
          --ctl-endpoint= control server network type (default: unix)
          --ctl-address=  control server address to connect (default:
                          /var/run/bblfshctl.sock)

[install command arguments]
  language:               language supported by the driver (optional)
  image:                  driver's image reference

Build information
  commit: v2.8.0
  date: 2018-09-27T18:07:48+0000
```

**Comment by dennwc** [comment] 2018-10-01 16:00
First of all, please don't use `latest` - it's expected to break in one way or another. Pin a specific stable version.

Second, why you need to install the driver twice in CI? Just wondering.

Also, this problem was already reported in #166 and contains a [description](https://github.com/bblfsh/bblfshd/issues/166#issuecomment-404454226) why we can't make it a warning in all cases. The change in v2.8.0 only (correctly) surfaced this error.

I will close it now as a duplicate of #166, but the issues will be resolved in one way or another.

**Closed by dennwc** 2018-10-01 16:00 UTC

**Comment by carlosms** [comment] 2018-10-03 14:34
Isn't `latest` the _latest stable_ version?

We've encountered this error here (and in other projects with similar travis config):
https://github.com/src-d/lookout/blob/master/.travis.yml#L37

We just had the install in place so it would either do the install for an empty travis cache, or silently fail if the driver was installed. I guess we will just add something like `|| true` to the driver install.
