### ISSUE TITLE
bblfshd:v2.11.8-drivers is broken after parsing csharp

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/bblfshd#259] opened 2019-03-06 09:56 UTC
discovered at https://github.com/src-d/empathy-sessions/issues/37#issuecomment-470045137

might be related to https://github.com/bblfsh/csharp-driver/issues/27
caused by https://github.com/bblfsh/csharp-driver/issues/32

While using `bblfsh/bblfshd:v2.11.8-drivers` image (the current latest), and parsing a `csharp` file I discovered that it screwed the bblfsh container up, and it won't be able to accept new parse requests.

even being fixed once `csharp-driver` is fixed, I think `bblfshd` could be also improved considering the following from my pov:
- if a driver causes an error, and it stops the processing (and it is logged into the `bblfshd` container), the error should be also exposed to `bblfshctl` and exit it with non `0` exit code, shouldn't it?
- if shuch thing happens, it should not affect the rest of the drivers, so the container should be able to parse other 

files using other drivers, shouldn't it? 

here is how to reproduce the bug:

```shell
$ docker run --rm -d --name bblfshd --privileged -p 9999:9432 bblfsh/bblfshd:v2.11.8-drivers

$ docker exec -it bblfshd bblfshctl driver list
+----------+-------------------------------+---------+--------+---------+----+------+------------------------------+
| LANGUAGE |             IMAGE             | VERSION | STATUS | CREATED | OS |  GO  |            NATIVE            |
+----------+-------------------------------+---------+--------+---------+----+------+------------------------------+
| ...                                                                                                              |
| csharp   | docker://bblfsh/csharp-driver | v1.4.0  | beta   | 2 weeks |    | 1.10 | microsoft/dotnet:2.1-runtime |
| ...                                                                                                              |
+----------+-------------------------------+---------+--------+---------+----+------+------------------------------+
Response time 737.109µs

# Parsing PHP files goes well
$ docker exec -it bblfshd bblfshctl parse /example.php
Status: Ok
Elapsed: 1.204853288s

Module {
.  Roles: Module
.  Children: {
.  .  0: Stmt_InlineHTML {
.  .  .  Roles: String,Literal,Incomplete
...

# Parsing CS files will break everything
$ docker exec -it bblfshd bblfshctl parse /example.cs

# the command takes forever with no output, so let's stop it
CTRL+C

# Let's try with some PHP again
$ docker exec -it bblfshd bblfshctl parse /example.php

# ooops; it was broken!
CTRL+C

# is there something in the container logs?
$ docker logs -f bblfshd
time="2019-03-06T06:45:11Z" level=info msg="bblfshd version: v2.11.8 (build: 2019-02-22T17:23:12+0000)"
time="2019-03-06T06:45:11Z" level=info msg="initializing runtime at /var/lib/bblfshd"
time="2019-03-06T06:45:11Z" level=info msg="server listening in 0.0.0.0:9432 (tcp)"
time="2019-03-06T06:45:11Z" level=info msg="control server listening in /var/run/bblfshctl.sock (unix)"
time="2019-03-06T06:48:39Z" level=info msg="php-driver version: v2.7.0 (build: 2019-02-06T08:44:31Z)" id=01d58w5qq3rkyk7149ca15x18v language=php
time="2019-03-06T06:48:39Z" level=info msg="server listening in /tmp/rpc.sock (unix)" id=01d58w5qq3rkyk7149ca15x18v language=php
time="2019-03-06T06:48:40Z" level=info msg="new driver instance started bblfsh/php-driver:latest (01d58w5qq3rkyk7149ca15x18v)"
panic: invalid tracer configuration: lookup localhost on 1.1.1.1:53: no such host

goroutine 1 [running]:
github.com/bblfsh/csharp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/server.RunNative(0xba9260, 0xc4200a0180, 0xb139e9, 0x6, 0xc420337ad0, 0x1, 0x1, 0xf0a260, 0x2, 0x2, ...)
	/go/src/github.com/bblfsh/csharp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/server/common.go:35 +0x162
github.com/bblfsh/csharp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/server.Run(0xb139e9, 0x6, 0xc420337ad0, 0x1, 0x1, 0xf0a260, 0x2, 0x2, 0xc42039b600, 0x2, ...)
	/go/src/github.com/bblfsh/csharp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/server/common.go:20 +0x74
main.main()
	/go/src/github.com/bblfsh/csharp-driver/driver/main.go:11 +0x5a
```

:point_down: Here is the offending file [examples/example.cs](https://github.com/dpordomingo/empathy-sessions/blob/master/4-engine/examples/example.cs) (but it also happened with many others)
<details><pre>
// A Hello World! program in C#.
using System;
namespace HelloWorld
{
    class Hello 
    {
        static void Main() 
        {
            Console.WriteLine("Hello World!");

            // Keep the console window open in debug mode.
            Console.WriteLine("Press any key to exit...");
            Console.ReadKey();
        }
    }
}
</pre></details>

**Comment by bzz** [comment] 2019-03-06 10:34
This seems like something that may have also been already addressed by @dennwc in #258 🤔

**Comment by dpordomingo** [comment] 2019-03-06 10:44
Great!
I'll subscribe to #258 and try to reproduce it again once there is a new `bblfshd` image

**Comment by dennwc** [comment] 2019-03-08 16:28
Still cannot reproduce it properly. The closest a can get is:
```
docker rm -f bblfshd
docker run -d --name bblfshd --privileged -p 9999:9432 -e JAEGER_AGENT_HOST=localhost bblfsh/bblfshd:v2.11.8-drivers
docker exec -it bblfshd bblfshctl driver list || exit 1
docker cp ../php-driver/fixtures/_integration.php bblfshd:/opt/bblfsh/etc/examples/php.php
docker cp ../csharp-driver/fixtures/_integration.cs bblfshd:/opt/bblfsh/etc/examples/csharp.cs
docker exec -it bblfshd bblfshctl parse /opt/bblfsh/etc/examples/php.php
docker exec -it bblfshd bblfshctl parse /opt/bblfsh/etc/examples/csharp.cs
docker exec -it bblfshd bblfshctl parse /opt/bblfsh/etc/examples/php.php
```
Still, it doesn't fail. If I change the `JAEGER_AGENT_HOST` to `non.existent` the `bblfshd` container fails to start, as expected. But I cannot make it run the `bblfshd`, but fail the driver with that option.

In any case, both problems should be fixed in the next `bblfshd` release thanks to the driver pool rewrite.

**Comment by bzz** [comment] 2019-03-19 11:53
Hey, @dpordomingo is there a chance you will have some spare cycles to verify @dennwc suggestions from https://github.com/bblfsh/bblfshd/issues/259#issuecomment-470989143 ? 
It would be very helpful, for the upcoming v2.11.9 release. Thanks again!

**Comment by dennwc** [comment] 2019-03-19 14:29
I think this is the same as https://github.com/bblfsh/sdk/issues/380. I've seen similar failure mode when working on a fix. If the native driver crashes, the request will just hang forever waiting to either write a request or read the response.

In case of https://github.com/bblfsh/sdk/issues/380 the driver crashed when a request was already written, so the function at least marked the driver as dead. In this case, the driver starts and crashes right after, so other requests assume that it's still alive and waiting forever to write the request.

Will add a test case to https://github.com/bblfsh/sdk/issues/380.

**Comment by carlosms** [comment] 2019-04-18 17:12
I've just come across this issue. In case it helps, here is my env:
bblfsh image `bblfsh/bblfshd:v2.12.1-drivers`.

file `hello.cs`
```csharp
class HelloWorld {
	static void Main() {
		System.Console.WriteLine("Hello World");
	}
}
```

Request made:
ParseRequest.content:
```
"class HelloWorld {\n\tstatic void Main() {\n\t\tSystem.Console.WriteLine(\"Hello World\");\n\t}\n}\n"
```
ParseRequest.options:
```
driver.ParseOptions{
  Mode: 8,
  Language: "c#",
  Filename: "./cmdtests/testdata/hello.cs",
}
```

bblfsh container logs:
```
panic: invalid tracer configuration: lookup localhost on 1.0.0.1:53: read udp 172.17.0.3:35272->1.0.0.1:53: i/o timeout

goroutine 1 [running]:
github.com/bblfsh/csharp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/server.RunNative(0xbad8e0, 0xc4200bc180, 0xb17d09, 0x6, 0xc42036e080, 0x1, 0x1, 0xf0f260, 0x2, 0x2, ...)
	/go/src/github.com/bblfsh/csharp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/server/common.go:35 +0x162
github.com/bblfsh/csharp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/server.Run(0xb17d09, 0x6, 0xc42036e080, 0x1, 0x1, 0xf0f260, 0x2, 0x2, 0xc4203cf340, 0x2, ...)
	/go/src/github.com/bblfsh/csharp-driver/vendor/gopkg.in/bblfsh/sdk.v2/driver/server/common.go:20 +0x74
main.main()
	/go/src/github.com/bblfsh/csharp-driver/driver/main.go:11 +0x5a
```

**Comment by dennwc** [comment] 2019-04-19 14:35
@carlosms It's not related to this issue. The issue you have is probably due to incorrect tracer configuration, as an error suggests. Try removing related [envs](https://github.com/bblfsh/bblfshd#enable-tracing) or set it to something valid.

Closing this, since an original issue was fixed.

**Closed by dennwc** 2019-04-19 14:35 UTC
Labels: bug

**Comment by carlosms** [comment] 2019-04-19 17:07
Pasting here for reference.
As discussed in slack, the problem is not incorrect config, as the container is using the default configuration.
The proposed workaround for now is to set the env var `JAEGER_DISABLED=1`.
